================================================================================
QUERY DOCUMENTATION
================================================================================
Query Name:         On Order & In Transit Data
Root File:          Atlas VMI_Open Upload File
Source Type:        SQL (Fabric Data Warehouse)
================================================================================

-- SOURCE:
--     Server: y2tjz7qjmziezabg56725hmy54-sll2odfgmm6ene2p55ripmzeaq
--             .datawarehouse.fabric.microsoft.com
--     Database: ERP
--     Base Object: dbo.vw_Orders_Base

-- SQL QUERY (embedded):
--     SELECT
--         CONCAT(o.CustomerNumber,' ',o.DeliveryAddressCode) AS CUSTOMER,
--         o.SKU AS CATN55,
--         o.OrderNumber AS ORDN55,
--         o.OrderQty AS CASES_ORD,
--         o.FulfillLineShippedQTY AS CASES_STP,
--         o.RequestedShipDate AS CSRQ40
--     FROM dbo.vw_Orders_Base o
--     WHERE o.LineStatusCode <> 'CANCELED'
--       AND o.OrderNumber NOT LIKE '%PALLET%'
--       AND o.SKU NOT LIKE '%PALLET%'
--       AND o.HeaderTypeCode NOT IN (
--             'BAILMENT - RETURN ORDER',
--             'BILLING ORDER',
--             'DESTRUCTION ORDER',
--             'INTERCOMPANY ORDER',
--             'RETURN ORDER')
--       AND o.RequestedShipDate
--             BETWEEN DATEADD(DAY, -3, CAST(GETDATE() AS DATE))
--                 AND CAST(GETDATE() AS DATE)

-- KEY COLUMNS RETURNED FROM SQL:
--     CUSTOMER    → CONCAT(CustomerNumber + ' ' + DeliveryAddressCode)
--                   mirrors the BuyList code format used in Append1
--     CATN55      → SKU (Sazerac product code from orders)
--     ORDN55      → Order Number
--     CASES_ORD   → Order Quantity
--     CASES_STP   → Fulfilled/Shipped Quantity
--     CSRQ40      → Requested Ship Date (filtered to last 3 days)

-- KEY TRANSFORMATIONS:
--     1. SQL pull with date window filter:
--            RequestedShipDate BETWEEN today-3 AND today
--     2. Sort by CATN55 ascending
--     3. Deduplicate on full record key
--        (CUSTOMER, ORDN55, CASES_ORD, CASES_STP, CATN55, CSRQ40)
--     4. LEFT JOIN to Oracle Buylist on CUSTOMER = CUSTOMER# and
--        CATN55 = CATN32 — returns CSRF32 (customer reference field)
--     5. Deduplicate again on full record key
--     6. Cast CSRQ40 to date type
--     7. Reorder columns
--     8. Duplicate CSRF32 column as SIRF32
--     9. Add "Data Source" column = "Oracle" (hardcoded label)
--     10. Deduplicate third time on full record key
--     11. Create Key = CUSTOMER + CSRF32
--     12. Add "PO Status 2" column = "In Transit" (hardcoded label)

-- OUTPUT COLUMNS:
--     CUSTOMER      → BuyList-format customer code (CustomerNumber + space + DeliveryAddressCode)
--     ORDN55        → Order number
--     CASES_ORD     → Ordered quantity
--     CASES_STP     → Shipped/fulfilled quantity
--     CATN55        → Sazerac SKU from orders
--     CSRQ40        → Requested ship date
--     CSRF32        → Customer reference field from BuyList join
--     SIRF32        → Duplicate of CSRF32
--     Data Source   → "Oracle" (hardcoded)
--     Key           → CUSTOMER + CSRF32 (composite join key)
--     PO Status 2   → "In Transit" (hardcoded)

-- JOINS TO:
--     Oracle Buylist → LEFT JOIN on CUSTOMER = CUSTOMER# and CATN55 = CATN32
--                      Returns: CSRF32
--     This query does NOT feed into Append1 directly.
--     Its connection to the final Atlas upload is unconfirmed — see Flag 1.

-- MAPS TO ATLAS COLUMN:
--     CASES_ORD or CASES_STP → In Transit (unconfirmed — see Flag 1)

================================================================================
FLAGS / NOTES — MUST ADDRESS BEFORE PYTHON BUILD
================================================================================

-- FLAG 1 — CONNECTION TO FINAL UPLOAD IS UNCONFIRMED:
--     This query exists in the workbook but does NOT appear in the
--     Append1 Table.Combine list. It is unclear where or how this
--     query connects to the final Atlas upload output.
--     Possible scenarios:
--       a) It is joined in a separate query outside Append1 that we
--          have not yet documented
--       b) It is joined via XLOOKUP in the Excel sheet after the
--          Power Query output is loaded to a worksheet
--       c) It feeds into a different workbook in the process
--       d) It is currently orphaned and not connected to anything
--     ACTION REQUIRED: this is the highest priority open question
--     in the entire process. Confirm with analyst exactly where
--     this query's output is consumed before building anything.

-- FLAG 2 — DATE WINDOW IS LAST 3 DAYS, NOT CURRENT:
--     The SQL filter pulls orders with RequestedShipDate between
--     today-3 and today. This means it captures orders up to 3 days
--     old, not just today's open orders. This could include already
--     fulfilled shipments depending on how CASES_STP is populated.
--     ACTION REQUIRED: confirm with analyst whether the 3-day window
--     is intentional and whether fulfilled orders should be included
--     or filtered out using CASES_STP > 0 or similar logic.
--     PYTHON BUILD NOTE: parameterize the date window so it can be
--     adjusted without touching pipeline code.

-- FLAG 3 — TRIPLE DEDUPLICATION:
--     Table.Distinct is called three times on the same key. This is
--     redundant after the first pass and suggests the query was built
--     incrementally without cleanup.
--     PYTHON BUILD NOTE: a single df.drop_duplicates() after all
--     joins are complete is sufficient.

-- FLAG 4 — CSRF32 DUPLICATED AS SIRF32 WITH NO PURPOSE:
--     CSRF32 is duplicated into a new column SIRF32 immediately after
--     being created, with no subsequent use of SIRF32 visible in this
--     query. This column appears to be an artifact of an earlier build
--     that was never cleaned up.
--     ACTION REQUIRED: confirm whether SIRF32 is used in a downstream
--     query or join. If not, remove it.

-- FLAG 5 — CUSTOMER KEY FORMAT MUST MATCH APPEND1:
--     CUSTOMER is built as CONCAT(CustomerNumber + ' ' + DeliveryAddressCode)
--     which should match the "Dpl Customer (key)" BuyList code format
--     used in Append1 (e.g. "1401158 001"). This is the join bridge
--     between in-transit and inventory data.
--     PYTHON BUILD NOTE: validate that the CUSTOMER format here exactly
--     matches the Dpl Customer (key) values in the distributor sources.
--     A format mismatch (e.g. leading zeros, spacing) would cause all
--     in-transit joins to fail silently.

-- FLAG 6 — CASES_ORD VS CASES_STP AMBIGUITY:
--     Both ordered quantity (CASES_ORD) and shipped quantity (CASES_STP)
--     are present. It is unclear which one maps to the Atlas In Transit
--     column. CASES_ORD represents what was ordered and CASES_STP
--     represents what has actually shipped — these are different things.
--     ACTION REQUIRED: confirm with analyst which quantity field should
--     populate the Atlas In Transit column and what the business definition
--     of "In Transit" is for this process.

-- FLAG 7 — ORDER TYPE EXCLUSIONS ARE HARDCODED:
--     Five HeaderTypeCode values are excluded in the SQL WHERE clause.
--     These exclusions are invisible to anyone reading the Power Query
--     output — they only exist in the embedded SQL string.
--     PYTHON BUILD NOTE: move these exclusions to a clearly documented
--     config list in the Python function so they are visible and
--     maintainable without editing SQL strings.

================================================================================
RAW M CODE
================================================================================

let
    Source = Sql.Database("y2tjz7qjmziezabg56725hmy54-sll2odfgmm6ene2p55ripmzeaq.datawarehouse.fabric.microsoft.com", "ERP", [Query="SELECT#(lf)    CONCAT(o.CustomerNumber,' ',o.DeliveryAddressCode) AS CUSTOMER,#(lf)    o.SKU AS CATN55,#(lf)    o.OrderNumber AS ORDN55,#(lf)    o.OrderQty AS CASES_ORD,#(lf)    o.FulfillLineShippedQTY AS CASES_STP,#(lf)    o.RequestedShipDate AS CSRQ40#(lf)FROM dbo.vw_Orders_Base o#(lf)WHERE o.LineStatusCode <> 'CANCELED'#(lf)  AND o.OrderNumber NOT LIKE '%PALLET%'#(lf)  AND o.SKU NOT LIKE '%PALLET%'#(lf)  AND o.HeaderTypeCode NOT IN (#(lf)        'BAILMENT - RETURN ORDER',#(lf)        'BILLING ORDER',#(lf)        'DESTRUCTION ORDER',#(lf)        'INTERCOMPANY ORDER',#(lf)        'RETURN ORDER')#(lf)  AND o.RequestedShipDate #(lf)        BETWEEN DATEADD(DAY, -3, CAST(GETDATE() AS DATE)) #(lf)            AND CAST(GETDATE() AS DATE)"]),
    #"Sorted Rows" = Table.Sort(Source,{{"CATN55", Order.Ascending}}),
    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"CUSTOMER", "ORDN55", "CASES_ORD", "CASES_STP", "CATN55", "CSRQ40"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Duplicates", {"CUSTOMER", "CATN55"}, #"Oracle Buylist", {"CUSTOMER#", "CATN32"}, "Oracle Buylist", JoinKind.LeftOuter),
    #"Expanded Oracle Buylist" = Table.ExpandTableColumn(#"Merged Queries", "Oracle Buylist", {"CSRF32"}, {"CSRF32"}),
    #"Removed Duplicates1" = Table.Distinct(#"Expanded Oracle Buylist", {"CUSTOMER", "ORDN55", "CASES_ORD", "CASES_STP", "CATN55", "CSRQ40"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates1",{{"CSRQ40", type date}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Changed Type",{"CUSTOMER", "ORDN55", "CASES_ORD", "CASES_STP", "CATN55", "CSRQ40"}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Reordered Columns1", "CSRF32", "SIRF32"),
    #"Reordered Columns2" = Table.ReorderColumns(#"Duplicated Column",{"CUSTOMER", "ORDN55", "CASES_ORD", "CASES_STP", "CATN55", "CSRQ40"}),
    #"Added Custom" = Table.AddColumn(#"Reordered Columns2", "Data Source", each "Oracle"),
    #"Reordered Columns4" = Table.ReorderColumns(#"Added Custom",{"CUSTOMER", "ORDN55", "CASES_ORD", "CASES_STP", "CATN55", "CSRQ40"}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Reordered Columns4",{"CUSTOMER", "ORDN55", "CASES_ORD", "CASES_STP", "CATN55", "CSRQ40"}),
    #"Removed Duplicates2" = Table.Distinct(#"Reordered Columns3", {"CUSTOMER", "ORDN55", "CASES_ORD", "CASES_STP", "CATN55", "CSRQ40"}),
    #"Added Custom1" = Table.AddColumn(#"Removed Duplicates2", "Key", each [CUSTOMER]&[CSRF32]),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "PO Status 2", each "In Transit")
in
    #"Added Custom2"

================================================================================
END OF FILE
================================================================================
